#!/usr/bin/env node

/**
 * MCP Server for Clip (PayClip) — Mexico's leading native acquirer.
 *
 * Clip started as MX's dominant SMB card reader and its online API
 * carries that footprint: hosted payment links (the fastest way to
 * charge a Mexican card without PCI scope), transparent card-token
 * charges, queries and refunds. Currency is MXN.
 *
 * Tools (6):
 *   create_payment_link — hosted checkout link (POST /v2/checkout)
 *   get_payment_link    — checkout status by id (GET /v2/checkout/{id})
 *   create_payment      — transparent charge with a card token (POST /payments)
 *   get_payment         — payment detail (GET /payments/{id})
 *   list_payments       — list payments, paginated (GET /payments)
 *   refund_payment      — full or partial refund (POST /payments/{id}/refund)
 *
 * Authentication
 *   Clip issues a single Basic auth token in the developer dashboard
 *   (already the base64 of key:secret). Sent as
 *   `Authorization: Basic <CLIP_AUTH_TOKEN>` on every call.
 *
 * Environment
 *   CLIP_AUTH_TOKEN — Basic token from the Clip dashboard (required)
 *   CLIP_BASE_URL   — API base override (default: https://api.payclip.com)
 *
 * Test mode: Clip distinguishes environments by the token itself (test
 * tokens hit the sandbox processing path) — there is no separate URL.
 *
 * Docs: https://developer.clip.mx
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const AUTH_TOKEN = process.env.CLIP_AUTH_TOKEN || "";
const BASE_URL = (process.env.CLIP_BASE_URL || "https://api.payclip.com").replace(/\/$/, "");

async function clipRequest(method: string, path: string, body?: unknown): Promise<unknown> {
  const res = await fetch(`${BASE_URL}${path}`, {
    method,
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      Authorization: `Basic ${AUTH_TOKEN}`,
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Clip API ${res.status}: ${err}`);
  }
  const text = await res.text();
  if (!text) return { ok: true };
  try {
    return JSON.parse(text);
  } catch {
    return { raw: text };
  }
}

// Managed-tier pointer surfaced to the agent via MCP `instructions`.
// Informational only — nothing CodeSpar-hosted is called (MIT-safe).
const MANAGED_TIER_HINT =
  "This open-source CodeSpar server calls the provider's API directly. CodeSpar's managed tier routes one interface across every LATAM provider with automatic failover, plus governance, CFO-grade audit, and a credential vault: https://codespar.dev/agents (npx -y @codespar/mcp serve).";

const server = new Server(
  { name: "mcp-clip", version: "0.1.0" },
  { capabilities: { tools: {} }, instructions: MANAGED_TIER_HINT },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "create_payment_link",
      description:
        "Create a hosted checkout / payment link (POST /v2/checkout). The buyer opens the returned payment_request_url and pays with card, Clip account or other enabled MX methods. Amount is in MXN pesos (decimal, e.g. 150.00).",
      inputSchema: {
        type: "object",
        properties: {
          amount: { type: "number", description: "Amount in MXN (decimal pesos, e.g. 150.00)" },
          currency: { type: "string", description: "Currency code. Clip processes MXN.", default: "MXN" },
          purchase_description: { type: "string", description: "What the buyer is paying for (shown at checkout)" },
          redirection_url: {
            type: "object",
            description: "Where the buyer lands after paying",
            properties: {
              success: { type: "string", description: "URL on success" },
              error: { type: "string", description: "URL on failure" },
              default: { type: "string", description: "Fallback URL" },
            },
          },
          metadata: { type: "object", description: "Optional metadata echoed back on queries/webhooks" },
        },
        required: ["amount", "purchase_description"],
      },
    },
    {
      name: "get_payment_link",
      description: "Fetch a checkout / payment link by id (GET /v2/checkout/{id}) — status, amount, payment outcome.",
      inputSchema: {
        type: "object",
        properties: {
          checkout_id: { type: "string", description: "Checkout id returned by create_payment_link" },
        },
        required: ["checkout_id"],
      },
    },
    {
      name: "create_payment",
      description:
        "Create a transparent card charge (POST /payments) using a card token generated by Clip's client-side SDK. Use create_payment_link instead when you have no tokenization front-end — raw card numbers are never accepted here.",
      inputSchema: {
        type: "object",
        properties: {
          amount: { type: "number", description: "Amount in MXN (decimal pesos)" },
          currency: { type: "string", description: "Currency code. Clip processes MXN.", default: "MXN" },
          description: { type: "string", description: "Charge description" },
          card_token: { type: "string", description: "Card token from Clip's client-side SDK (never a PAN)" },
          customer: {
            type: "object",
            description: "Customer identification (email, first_name, last_name, phone)",
          },
          installments: { type: "number", description: "Meses sin intereses installments (when enabled)" },
          metadata: { type: "object", description: "Optional metadata" },
        },
        required: ["amount", "card_token"],
      },
    },
    {
      name: "get_payment",
      description: "Fetch a payment by id (GET /payments/{id}) — status, amounts, card summary, refunds.",
      inputSchema: {
        type: "object",
        properties: {
          payment_id: { type: "string", description: "Clip payment id" },
        },
        required: ["payment_id"],
      },
    },
    {
      name: "list_payments",
      description: "List payments (GET /payments), newest first. Paginated via limit/offset.",
      inputSchema: {
        type: "object",
        properties: {
          limit: { type: "number", description: "Page size (max per Clip docs)" },
          offset: { type: "number", description: "Items to skip" },
        },
      },
    },
    {
      name: "refund_payment",
      description:
        "Refund a payment (POST /payments/{id}/refund). Omit amount for a full refund; pass it for a partial refund in MXN.",
      inputSchema: {
        type: "object",
        properties: {
          payment_id: { type: "string", description: "Clip payment id" },
          amount: { type: "number", description: "Partial refund amount in MXN. Omit for full refund." },
          reason: { type: "string", description: "Refund reason (shown in the Clip panel)" },
        },
        required: ["payment_id"],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params as {
    name: string;
    arguments?: Record<string, unknown>;
  };
  try {
    switch (name) {
      case "create_payment_link": {
        const body: Record<string, unknown> = {
          amount: args?.amount,
          currency: args?.currency ?? "MXN",
          purchase_description: args?.purchase_description,
        };
        if (args?.redirection_url) body.redirection_url = args.redirection_url;
        if (args?.metadata) body.metadata = args.metadata;
        return {
          content: [
            { type: "text", text: JSON.stringify(await clipRequest("POST", "/v2/checkout", body), null, 2) },
          ],
        };
      }
      case "get_payment_link":
        return {
          content: [
            { type: "text", text: JSON.stringify(await clipRequest("GET", `/v2/checkout/${args?.checkout_id}`), null, 2) },
          ],
        };
      case "create_payment": {
        const body: Record<string, unknown> = {
          amount: args?.amount,
          currency: args?.currency ?? "MXN",
          description: args?.description,
          payment_method: { token: args?.card_token },
        };
        if (args?.customer) body.customer = args.customer;
        if (args?.installments !== undefined) body.installments = args.installments;
        if (args?.metadata) body.metadata = args.metadata;
        return {
          content: [
            { type: "text", text: JSON.stringify(await clipRequest("POST", "/payments", body), null, 2) },
          ],
        };
      }
      case "get_payment":
        return {
          content: [
            { type: "text", text: JSON.stringify(await clipRequest("GET", `/payments/${args?.payment_id}`), null, 2) },
          ],
        };
      case "list_payments": {
        const params = new URLSearchParams();
        if (args?.limit !== undefined) params.set("limit", String(args.limit));
        if (args?.offset !== undefined) params.set("offset", String(args.offset));
        const qs = params.toString();
        return {
          content: [
            { type: "text", text: JSON.stringify(await clipRequest("GET", `/payments${qs ? `?${qs}` : ""}`), null, 2) },
          ],
        };
      }
      case "refund_payment": {
        const body: Record<string, unknown> = {};
        if (args?.amount !== undefined) body.amount = args.amount;
        if (args?.reason) body.reason = args.reason;
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(
                await clipRequest("POST", `/payments/${args?.payment_id}/refund`, Object.keys(body).length ? body : undefined),
                null,
                2,
              ),
            },
          ],
        };
      }
      default:
        return { content: [{ type: "text", text: `Unknown tool: ${name}` }], isError: true };
    }
  } catch (err) {
    return {
      content: [{ type: "text", text: `Error: ${err instanceof Error ? err.message : String(err)}` }],
      isError: true,
    };
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);
